# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
